services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: webchat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: webchat
      POSTGRES_PASSWORD: webchat
      POSTGRES_DB: webchat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
